// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/pfcp/v1/control.proto

package pfcpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Pdrs          []*PDR                 `protobuf:"bytes,2,rep,name=pdrs,proto3" json:"pdrs,omitempty"`
	Fars          []*FAR                 `protobuf:"bytes,3,rep,name=fars,proto3" json:"fars,omitempty"`
	Qers          []*QER                 `protobuf:"bytes,4,rep,name=qers,proto3" json:"qers,omitempty"`
	Urrs          []*URR                 `protobuf:"bytes,5,rep,name=urrs,proto3" json:"urrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateSessionRequest) GetPdrs() []*PDR {
	if x != nil {
		return x.Pdrs
	}
	return nil
}

func (x *CreateSessionRequest) GetFars() []*FAR {
	if x != nil {
		return x.Fars
	}
	return nil
}

func (x *CreateSessionRequest) GetQers() []*QER {
	if x != nil {
		return x.Qers
	}
	return nil
}

func (x *CreateSessionRequest) GetUrrs() []*URR {
	if x != nil {
		return x.Urrs
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seid          uint64                 `protobuf:"varint,1,opt,name=seid,proto3" json:"seid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSeid() uint64 {
	if x != nil {
		return x.Seid
	}
	return 0
}

type ModifySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seid          uint64                 `protobuf:"varint,1,opt,name=seid,proto3" json:"seid,omitempty"`
	Pdrs          []*PDR                 `protobuf:"bytes,2,rep,name=pdrs,proto3" json:"pdrs,omitempty"`
	Fars          []*FAR                 `protobuf:"bytes,3,rep,name=fars,proto3" json:"fars,omitempty"`
	Qers          []*QER                 `protobuf:"bytes,4,rep,name=qers,proto3" json:"qers,omitempty"`
	Urrs          []*URR                 `protobuf:"bytes,5,rep,name=urrs,proto3" json:"urrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifySessionRequest) Reset() {
	*x = ModifySessionRequest{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySessionRequest) ProtoMessage() {}

func (x *ModifySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySessionRequest.ProtoReflect.Descriptor instead.
func (*ModifySessionRequest) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ModifySessionRequest) GetSeid() uint64 {
	if x != nil {
		return x.Seid
	}
	return 0
}

func (x *ModifySessionRequest) GetPdrs() []*PDR {
	if x != nil {
		return x.Pdrs
	}
	return nil
}

func (x *ModifySessionRequest) GetFars() []*FAR {
	if x != nil {
		return x.Fars
	}
	return nil
}

func (x *ModifySessionRequest) GetQers() []*QER {
	if x != nil {
		return x.Qers
	}
	return nil
}

func (x *ModifySessionRequest) GetUrrs() []*URR {
	if x != nil {
		return x.Urrs
	}
	return nil
}

type ModifySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifySessionResponse) Reset() {
	*x = ModifySessionResponse{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySessionResponse) ProtoMessage() {}

func (x *ModifySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySessionResponse.ProtoReflect.Descriptor instead.
func (*ModifySessionResponse) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ModifySessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seid          uint64                 `protobuf:"varint,1,opt,name=seid,proto3" json:"seid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSessionRequest) GetSeid() uint64 {
	if x != nil {
		return x.Seid
	}
	return 0
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAssociationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssociationsRequest) Reset() {
	*x = ListAssociationsRequest{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssociationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssociationsRequest) ProtoMessage() {}

func (x *ListAssociationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssociationsRequest.ProtoReflect.Descriptor instead.
func (*ListAssociationsRequest) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{6}
}

type ListAssociationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Associations  []*Association         `protobuf:"bytes,1,rep,name=associations,proto3" json:"associations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssociationsResponse) Reset() {
	*x = ListAssociationsResponse{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssociationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssociationsResponse) ProtoMessage() {}

func (x *ListAssociationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssociationsResponse.ProtoReflect.Descriptor instead.
func (*ListAssociationsResponse) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ListAssociationsResponse) GetAssociations() []*Association {
	if x != nil {
		return x.Associations
	}
	return nil
}

type Association struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	EstablishedAt int64                  `protobuf:"varint,3,opt,name=established_at,json=establishedAt,proto3" json:"established_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Association) Reset() {
	*x = Association{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Association) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Association) ProtoMessage() {}

func (x *Association) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Association.ProtoReflect.Descriptor instead.
func (*Association) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *Association) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Association) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *Association) GetEstablishedAt() int64 {
	if x != nil {
		return x.EstablishedAt
	}
	return 0
}

type PDR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Precedence    uint32                 `protobuf:"varint,2,opt,name=precedence,proto3" json:"precedence,omitempty"`
	Pdi           *PacketDetectionInfo   `protobuf:"bytes,3,opt,name=pdi,proto3" json:"pdi,omitempty"`
	FarId         uint32                 `protobuf:"varint,4,opt,name=far_id,json=farId,proto3" json:"far_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDR) Reset() {
	*x = PDR{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDR) ProtoMessage() {}

func (x *PDR) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDR.ProtoReflect.Descriptor instead.
func (*PDR) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *PDR) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PDR) GetPrecedence() uint32 {
	if x != nil {
		return x.Precedence
	}
	return 0
}

func (x *PDR) GetPdi() *PacketDetectionInfo {
	if x != nil {
		return x.Pdi
	}
	return nil
}

func (x *PDR) GetFarId() uint32 {
	if x != nil {
		return x.FarId
	}
	return 0
}

type PacketDetectionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceInterface uint32                 `protobuf:"varint,1,opt,name=source_interface,json=sourceInterface,proto3" json:"source_interface,omitempty"`
	SdfFilter       string                 `protobuf:"bytes,2,opt,name=sdf_filter,json=sdfFilter,proto3" json:"sdf_filter,omitempty"`
	UeIpAddress     string                 `protobuf:"bytes,3,opt,name=ue_ip_address,json=ueIpAddress,proto3" json:"ue_ip_address,omitempty"`
	NetworkInstance string                 `protobuf:"bytes,4,opt,name=network_instance,json=networkInstance,proto3" json:"network_instance,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,5,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PacketDetectionInfo) Reset() {
	*x = PacketDetectionInfo{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketDetectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketDetectionInfo) ProtoMessage() {}

func (x *PacketDetectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketDetectionInfo.ProtoReflect.Descriptor instead.
func (*PacketDetectionInfo) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *PacketDetectionInfo) GetSourceInterface() uint32 {
	if x != nil {
		return x.SourceInterface
	}
	return 0
}

func (x *PacketDetectionInfo) GetSdfFilter() string {
	if x != nil {
		return x.SdfFilter
	}
	return ""
}

func (x *PacketDetectionInfo) GetUeIpAddress() string {
	if x != nil {
		return x.UeIpAddress
	}
	return ""
}

func (x *PacketDetectionInfo) GetNetworkInstance() string {
	if x != nil {
		return x.NetworkInstance
	}
	return ""
}

func (x *PacketDetectionInfo) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type FAR struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplyAction      uint32                 `protobuf:"varint,2,opt,name=apply_action,json=applyAction,proto3" json:"apply_action,omitempty"`
	ForwardingParams *ForwardingParameters  `protobuf:"bytes,3,opt,name=forwarding_params,json=forwardingParams,proto3" json:"forwarding_params,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FAR) Reset() {
	*x = FAR{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FAR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FAR) ProtoMessage() {}

func (x *FAR) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FAR.ProtoReflect.Descriptor instead.
func (*FAR) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *FAR) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FAR) GetApplyAction() uint32 {
	if x != nil {
		return x.ApplyAction
	}
	return 0
}

func (x *FAR) GetForwardingParams() *ForwardingParameters {
	if x != nil {
		return x.ForwardingParams
	}
	return nil
}

type ForwardingParameters struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DestinationInterface uint32                 `protobuf:"varint,1,opt,name=destination_interface,json=destinationInterface,proto3" json:"destination_interface,omitempty"`
	NetworkInstance      string                 `protobuf:"bytes,2,opt,name=network_instance,json=networkInstance,proto3" json:"network_instance,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ForwardingParameters) Reset() {
	*x = ForwardingParameters{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardingParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardingParameters) ProtoMessage() {}

func (x *ForwardingParameters) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardingParameters.ProtoReflect.Descriptor instead.
func (*ForwardingParameters) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *ForwardingParameters) GetDestinationInterface() uint32 {
	if x != nil {
		return x.DestinationInterface
	}
	return 0
}

func (x *ForwardingParameters) GetNetworkInstance() string {
	if x != nil {
		return x.NetworkInstance
	}
	return ""
}

type QER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GateStatus    uint32                 `protobuf:"varint,2,opt,name=gate_status,json=gateStatus,proto3" json:"gate_status,omitempty"`
	MbrUplink     uint64                 `protobuf:"varint,3,opt,name=mbr_uplink,json=mbrUplink,proto3" json:"mbr_uplink,omitempty"`
	MbrDownlink   uint64                 `protobuf:"varint,4,opt,name=mbr_downlink,json=mbrDownlink,proto3" json:"mbr_downlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QER) Reset() {
	*x = QER{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QER) ProtoMessage() {}

func (x *QER) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QER.ProtoReflect.Descriptor instead.
func (*QER) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *QER) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QER) GetGateStatus() uint32 {
	if x != nil {
		return x.GateStatus
	}
	return 0
}

func (x *QER) GetMbrUplink() uint64 {
	if x != nil {
		return x.MbrUplink
	}
	return 0
}

func (x *QER) GetMbrDownlink() uint64 {
	if x != nil {
		return x.MbrDownlink
	}
	return 0
}

type URR struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MeasurementMethod uint32                 `protobuf:"varint,2,opt,name=measurement_method,json=measurementMethod,proto3" json:"measurement_method,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *URR) Reset() {
	*x = URR{}
	mi := &file_api_pfcp_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URR) ProtoMessage() {}

func (x *URR) ProtoReflect() protoreflect.Message {
	mi := &file_api_pfcp_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URR.ProtoReflect.Descriptor instead.
func (*URR) Descriptor() ([]byte, []int) {
	return file_api_pfcp_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *URR) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *URR) GetMeasurementMethod() uint32 {
	if x != nil {
		return x.MeasurementMethod
	}
	return 0
}

var File_api_pfcp_v1_control_proto protoreflect.FileDescriptor

const file_api_pfcp_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x19api/pfcp/v1/control.proto\x12\apfcp.v1\"\xb7\x01\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12 \n" +
	"\x04pdrs\x18\x02 \x03(\v2\f.pfcp.v1.PDRR\x04pdrs\x12 \n" +
	"\x04fars\x18\x03 \x03(\v2\f.pfcp.v1.FARR\x04fars\x12 \n" +
	"\x04qers\x18\x04 \x03(\v2\f.pfcp.v1.QERR\x04qers\x12 \n" +
	"\x04urrs\x18\x05 \x03(\v2\f.pfcp.v1.URRR\x04urrs\"+\n" +
	"\x15CreateSessionResponse\x12\x12\n" +
	"\x04seid\x18\x01 \x01(\x04R\x04seid\"\xb2\x01\n" +
	"\x14ModifySessionRequest\x12\x12\n" +
	"\x04seid\x18\x01 \x01(\x04R\x04seid\x12 \n" +
	"\x04pdrs\x18\x02 \x03(\v2\f.pfcp.v1.PDRR\x04pdrs\x12 \n" +
	"\x04fars\x18\x03 \x03(\v2\f.pfcp.v1.FARR\x04fars\x12 \n" +
	"\x04qers\x18\x04 \x03(\v2\f.pfcp.v1.QERR\x04qers\x12 \n" +
	"\x04urrs\x18\x05 \x03(\v2\f.pfcp.v1.URRR\x04urrs\"1\n" +
	"\x15ModifySessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x14DeleteSessionRequest\x12\x12\n" +
	"\x04seid\x18\x01 \x01(\x04R\x04seid\"1\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x19\n" +
	"\x17ListAssociationsRequest\"T\n" +
	"\x18ListAssociationsResponse\x128\n" +
	"\fassociations\x18\x01 \x03(\v2\x14.pfcp.v1.AssociationR\fassociations\"n\n" +
	"\vAssociation\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vremote_addr\x18\x02 \x01(\tR\n" +
	"remoteAddr\x12%\n" +
	"\x0eestablished_at\x18\x03 \x01(\x03R\restablishedAt\"|\n" +
	"\x03PDR\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1e\n" +
	"\n" +
	"precedence\x18\x02 \x01(\rR\n" +
	"precedence\x12.\n" +
	"\x03pdi\x18\x03 \x01(\v2\x1c.pfcp.v1.PacketDetectionInfoR\x03pdi\x12\x15\n" +
	"\x06far_id\x18\x04 \x01(\rR\x05farId\"\xd5\x01\n" +
	"\x13PacketDetectionInfo\x12)\n" +
	"\x10source_interface\x18\x01 \x01(\rR\x0fsourceInterface\x12\x1d\n" +
	"\n" +
	"sdf_filter\x18\x02 \x01(\tR\tsdfFilter\x12\"\n" +
	"\rue_ip_address\x18\x03 \x01(\tR\vueIpAddress\x12)\n" +
	"\x10network_instance\x18\x04 \x01(\tR\x0fnetworkInstance\x12%\n" +
	"\x0eapplication_id\x18\x05 \x01(\tR\rapplicationId\"\x84\x01\n" +
	"\x03FAR\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\fapply_action\x18\x02 \x01(\rR\vapplyAction\x12J\n" +
	"\x11forwarding_params\x18\x03 \x01(\v2\x1d.pfcp.v1.ForwardingParametersR\x10forwardingParams\"v\n" +
	"\x14ForwardingParameters\x123\n" +
	"\x15destination_interface\x18\x01 \x01(\rR\x14destinationInterface\x12)\n" +
	"\x10network_instance\x18\x02 \x01(\tR\x0fnetworkInstance\"x\n" +
	"\x03QER\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vgate_status\x18\x02 \x01(\rR\n" +
	"gateStatus\x12\x1d\n" +
	"\n" +
	"mbr_uplink\x18\x03 \x01(\x04R\tmbrUplink\x12!\n" +
	"\fmbr_downlink\x18\x04 \x01(\x04R\vmbrDownlink\"D\n" +
	"\x03URR\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12-\n" +
	"\x12measurement_method\x18\x02 \x01(\rR\x11measurementMethod2\xd7\x02\n" +
	"\fControlPlane\x12N\n" +
	"\rCreateSession\x12\x1d.pfcp.v1.CreateSessionRequest\x1a\x1e.pfcp.v1.CreateSessionResponse\x12N\n" +
	"\rModifySession\x12\x1d.pfcp.v1.ModifySessionRequest\x1a\x1e.pfcp.v1.ModifySessionResponse\x12N\n" +
	"\rDeleteSession\x12\x1d.pfcp.v1.DeleteSessionRequest\x1a\x1e.pfcp.v1.DeleteSessionResponse\x12W\n" +
	"\x10ListAssociations\x12 .pfcp.v1.ListAssociationsRequest\x1a!.pfcp.v1.ListAssociationsResponseB7Z5github.com/veesix-networks/pfcp-go/api/pfcp/v1;pfcpv1b\x06proto3"

var (
	file_api_pfcp_v1_control_proto_rawDescOnce sync.Once
	file_api_pfcp_v1_control_proto_rawDescData []byte
)

func file_api_pfcp_v1_control_proto_rawDescGZIP() []byte {
	file_api_pfcp_v1_control_proto_rawDescOnce.Do(func() {
		file_api_pfcp_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pfcp_v1_control_proto_rawDesc), len(file_api_pfcp_v1_control_proto_rawDesc)))
	})
	return file_api_pfcp_v1_control_proto_rawDescData
}

var file_api_pfcp_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_pfcp_v1_control_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),     // 0: pfcp.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),    // 1: pfcp.v1.CreateSessionResponse
	(*ModifySessionRequest)(nil),     // 2: pfcp.v1.ModifySessionRequest
	(*ModifySessionResponse)(nil),    // 3: pfcp.v1.ModifySessionResponse
	(*DeleteSessionRequest)(nil),     // 4: pfcp.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),    // 5: pfcp.v1.DeleteSessionResponse
	(*ListAssociationsRequest)(nil),  // 6: pfcp.v1.ListAssociationsRequest
	(*ListAssociationsResponse)(nil), // 7: pfcp.v1.ListAssociationsResponse
	(*Association)(nil),              // 8: pfcp.v1.Association
	(*PDR)(nil),                      // 9: pfcp.v1.PDR
	(*PacketDetectionInfo)(nil),      // 10: pfcp.v1.PacketDetectionInfo
	(*FAR)(nil),                      // 11: pfcp.v1.FAR
	(*ForwardingParameters)(nil),     // 12: pfcp.v1.ForwardingParameters
	(*QER)(nil),                      // 13: pfcp.v1.QER
	(*URR)(nil),                      // 14: pfcp.v1.URR
}
var file_api_pfcp_v1_control_proto_depIdxs = []int32{
	9,  // 0: pfcp.v1.CreateSessionRequest.pdrs:type_name -> pfcp.v1.PDR
	11, // 1: pfcp.v1.CreateSessionRequest.fars:type_name -> pfcp.v1.FAR
	13, // 2: pfcp.v1.CreateSessionRequest.qers:type_name -> pfcp.v1.QER
	14, // 3: pfcp.v1.CreateSessionRequest.urrs:type_name -> pfcp.v1.URR
	9,  // 4: pfcp.v1.ModifySessionRequest.pdrs:type_name -> pfcp.v1.PDR
	11, // 5: pfcp.v1.ModifySessionRequest.fars:type_name -> pfcp.v1.FAR
	13, // 6: pfcp.v1.ModifySessionRequest.qers:type_name -> pfcp.v1.QER
	14, // 7: pfcp.v1.ModifySessionRequest.urrs:type_name -> pfcp.v1.URR
	8,  // 8: pfcp.v1.ListAssociationsResponse.associations:type_name -> pfcp.v1.Association
	10, // 9: pfcp.v1.PDR.pdi:type_name -> pfcp.v1.PacketDetectionInfo
	12, // 10: pfcp.v1.FAR.forwarding_params:type_name -> pfcp.v1.ForwardingParameters
	0,  // 11: pfcp.v1.ControlPlane.CreateSession:input_type -> pfcp.v1.CreateSessionRequest
	2,  // 12: pfcp.v1.ControlPlane.ModifySession:input_type -> pfcp.v1.ModifySessionRequest
	4,  // 13: pfcp.v1.ControlPlane.DeleteSession:input_type -> pfcp.v1.DeleteSessionRequest
	6,  // 14: pfcp.v1.ControlPlane.ListAssociations:input_type -> pfcp.v1.ListAssociationsRequest
	1,  // 15: pfcp.v1.ControlPlane.CreateSession:output_type -> pfcp.v1.CreateSessionResponse
	3,  // 16: pfcp.v1.ControlPlane.ModifySession:output_type -> pfcp.v1.ModifySessionResponse
	5,  // 17: pfcp.v1.ControlPlane.DeleteSession:output_type -> pfcp.v1.DeleteSessionResponse
	7,  // 18: pfcp.v1.ControlPlane.ListAssociations:output_type -> pfcp.v1.ListAssociationsResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_pfcp_v1_control_proto_init() }
func file_api_pfcp_v1_control_proto_init() {
	if File_api_pfcp_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pfcp_v1_control_proto_rawDesc), len(file_api_pfcp_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pfcp_v1_control_proto_goTypes,
		DependencyIndexes: file_api_pfcp_v1_control_proto_depIdxs,
		MessageInfos:      file_api_pfcp_v1_control_proto_msgTypes,
	}.Build()
	File_api_pfcp_v1_control_proto = out.File
	file_api_pfcp_v1_control_proto_goTypes = nil
	file_api_pfcp_v1_control_proto_depIdxs = nil
}
